### ISSUE TITLE
create new database structure

### ISSUE THREAD

**Issue by emoltz** [emoltz/budget-tracker#82]
**Interfaces**
- [x] New: MonthSummary (needs modification)
- [x] Modify: Category to include "summary" info and icon info
- [x] Create: Budgets

**Firebase Calls**
- [x] Modify: create user (`saveUserToDatabase`) that initializes user with new defaults
- [x] Modify: add expense (`sendExpenseToFirebase`)
- [x] New: get summary from month summary
- [x] #102
- [x] Modify: add category (`addCategory`)
- [x] Modify: change category icon (`changeCategoryIcon`)
- [x] New: create default budgets

**Misc**
- [x] #100
- [x] Way to store budgets / connect with categories
- [x] #94

![image](https://github.com/emoltz/budget-tracker/assets/13296034/c22576b0-1b11-40f0-8745-db599bf2299a)

**Comment by emoltz** [comment]
Quick thought: change `Budgets` to `monthly_budgets` and then add another `yearly_budgets` table. Budgets will be monthly by default. This will allow us to remove `is_weekly` etc from the budgets table as well.

**Comment by adelaidemz** [comment]
At the moment:

For each month there is a summary doc, which has a grand total but also points to a collection of category summary docs, which implement the Category interface/class. The category docs are created when a new expense is added in the corresponding category, and at creation budget and icon info are pulled from their respective places to save in the doc.

>> This means that budget and icon are duplicated, so should either

1. update in both places when they are changed OR 
2. change to only store one copy of each, and query those whenever getCurrentSummary is called (effectively using CategoryClass on the read side rather than the write side)
